In [5]:
# import networkx as nx
import numpy as np
arr = np.loadtxt('../true_distance')
arr2 = np.loadtxt('../answedel')
arr2.sort(axis=1)


In [97]:
finalanswer = []
n = 100*2
M = np.zeros((n,n))+np.inf
for a in arr:
    i = int(a[0])
    j = int(a[1])
    val = a[2]
    M[i][j] = val
    M[j][i] = val
for i in range(n):
    M[i][i] = np.inf

gp = dict()
for i in range(int(n/2)):
    gp[i] = np.array([i])

index = 100
done = np.array([])
for i in range(100):
    zen = 0
    sorted_array = np.dstack(np.unravel_index(np.argsort(M.ravel()), (n, n)))[0]
    while(True):
        a  = sorted_array[zen]
        zen += 1
        point1, point2 = a
        if np.where(done==point1)[0].shape[0] == 0 and np.where(done==point2)[0].shape[0] == 0:
            break
        else:
            pass
#             print (done, point1, point2)
    print ( M[a[0]][a[1]], a, i)
    finalanswer += [[index, a[0], a[1]]]
    done = np.concatenate([done, sorted(a)])
    gp[index] = np.concatenate([gp[point1], gp[point2]])
    
    for ii in range(index):
        i = index - ii - 1
        sum=0
        terms = 0
        if np.where(done==i)[0].shape[0] > 0 :
            continue
        for p1 in gp[index]:
            for p2 in gp[i]:
                if i==index:
                    continue
                terms += 1
                if p1 > n/2 or p2 > n/2:
                    print ("Cry")
                if M[p1][p2] > 1000000:
                    print (p1, p2,gp[index], gp[i], index, done, i)
                sum += M[p1][p2]
        M[index][i] = sum/terms
        print (gp[index], gp[i], M[index][i])
        M[i][index] = sum/terms
        M[index][index] = np.inf
    index +=1
finalanswer = np.array(finalanswer)

2375.44 [78  9] 0
[78  9] [99] 5641.415
[78  9] [98] 7093.775
[78  9] [97] 5279.18
[78  9] [96] 4066.405
[78  9] [95] 6107.4
[78  9] [94] 6404.635
[78  9] [93] 3894.95
[78  9] [92] 4764.32
[78  9] [91] 5556.785
[78  9] [90] 8107.065
[78  9] [89] 9619.84
[78  9] [88] 8423.885
[78  9] [87] 3544.025
[78  9] [86] 4012.435
[78  9] [85] 5068.67
[78  9] [84] 4374.78
[78  9] [83] 6740.625
[78  9] [82] 6095.62
[78  9] [81] 6179.0
[78  9] [80] 4804.7
[78  9] [79] 6760.39
[78  9] [77] 6755.68
[78  9] [76] 4723.925
[78  9] [75] 7280.095
[78  9] [74] 7025.08
[78  9] [73] 3405.165
[78  9] [72] 11841.7
[78  9] [71] 17783.8
[78  9] [70] 4494.18
[78  9] [69] 11801.7
[78  9] [68] 5805.715
[78  9] [67] 3312.175
[78  9] [66] 4671.7
[78  9] [65] 4272.665
[78  9] [64] 9150.255
[78  9] [63] 10043.325
[78  9] [62] 14397.1
[78  9] [61] 4881.6
[78  9] [60] 4702.965
[78  9] [59] 6350.165
[78  9] [58] 5349.395
[78  9] [57] 13549.05
[78  9] [56] 3158.72
[78  9] [55] 7076.56
[78  9] [54] 4231.02
[78  9] [53] 3704.2

[20 56] [60] 5209.335
[20 56] [59] 8226.14
[20 56] [58] 7429.205
[20 56] [57] 16346.15
[20 56] [55] 8411.9
[20 56] [54] 5621.885
[20 56] [53] 5203.05
[20 56] [52] 10344.835
[20 56] [51] 6090.85
[20 56] [50] 10283.35
[20 56] [49] 7081.87
[20 56] [48] 31530.8
[20 56] [47] 6531.985
[20 56] [46] 8121.94
[20 56] [44] 6064.175
[20 56] [43] 5527.79
[20 56] [42] 5356.33
[20 56] [41] 7119.03
[20 56] [40] 7483.38
[20 56] [39] 4637.59
[20 56] [38] 5408.115
[20 56] [37] 4353.51
[20 56] [36] 10173.8
[20 56] [35] 5632.01
[20 56] [34] 6288.155
[20 56] [33] 6477.705
[20 56] [32] 8806.76
[20 56] [31] 4879.795
[20 56] [30] 9111.545
[20 56] [29] 10803.16
[20 56] [27] 5914.145
[20 56] [26] 13223.85
[20 56] [25] 5139.33
[20 56] [24] 7442.56
[20 56] [23] 5705.575
[20 56] [22] 9326.34
[20 56] [21] 8450.81
[20 56] [19] 9972.33
[20 56] [18] 10393.6
[20 56] [17] 28621.5
[20 56] [16] 10098.705
[20 56] [15] 9055.235
[20 56] [14] 6318.625
[20 56] [13] 4906.015
[20 56] [12] 5910.19
[20 56] [11] 8529.35
[20 56] [10]

[21 23] [4] 15035.0
[21 23] [2] 11635.49
[21 23] [0] 10389.6
3043.1925 [105 103] 9
[13 87 28 80] [21 23] 6027.1275
[13 87 28 80] [ 1 73] 4471.31875
[13 87 28 80] [39 78  9] 3656.2375
[13 87 28 80] [20 56] 5275.55375
[13 87 28 80] [ 3 65] 5880.1375
[13 87 28 80] [45  6] 4145.3875
[13 87 28 80] [99] 7648.13
[13 87 28 80] [98] 4535.2075
[13 87 28 80] [97] 4821.4875
[13 87 28 80] [96] 4207.7425
[13 87 28 80] [95] 5692.57
[13 87 28 80] [94] 4137.4725
[13 87 28 80] [93] 4745.1825
[13 87 28 80] [92] 4156.1625
[13 87 28 80] [91] 7945.19
[13 87 28 80] [90] 7380.535
[13 87 28 80] [89] 11837.525
[13 87 28 80] [88] 6190.15
[13 87 28 80] [86] 4715.075
[13 87 28 80] [85] 8869.1125
[13 87 28 80] [84] 4269.2825
[13 87 28 80] [83] 4817.5175
[13 87 28 80] [82] 7537.5675
[13 87 28 80] [81] 5065.2425
[13 87 28 80] [79] 7744.3
[13 87 28 80] [77] 6465.8625
[13 87 28 80] [76] 6163.435
[13 87 28 80] [75] 8994.9325
[13 87 28 80] [74] 11241.4725
[13 87 28 80] [72] 13777.375
[13 87 28 80] [71] 11827.1
[13 87 28 

[ 1 73 39 78  9] [40] 5793.83
[ 1 73 39 78  9] [38] 3631.638
[ 1 73 39 78  9] [37] 5785.42
[ 1 73 39 78  9] [36] 6351.374
[ 1 73 39 78  9] [35] 3862.79
[ 1 73 39 78  9] [34] 6702.818
[ 1 73 39 78  9] [33] 5920.264
[ 1 73 39 78  9] [32] 6112.642
[ 1 73 39 78  9] [31] 4276.99
[ 1 73 39 78  9] [30] 6609.672
[ 1 73 39 78  9] [29] 10506.844
[ 1 73 39 78  9] [27] 5512.178
[ 1 73 39 78  9] [26] 10265.544
[ 1 73 39 78  9] [25] 5270.382
[ 1 73 39 78  9] [24] 5993.834
[ 1 73 39 78  9] [22] 8151.402
[ 1 73 39 78  9] [18] 9393.334
[ 1 73 39 78  9] [16] 8276.682
[ 1 73 39 78  9] [15] 7133.624
[ 1 73 39 78  9] [14] 4818.914
[ 1 73 39 78  9] [12] 6209.878
[ 1 73 39 78  9] [11] 7503.526
[ 1 73 39 78  9] [10] 10935.014
[ 1 73 39 78  9] [8] 4845.094
[ 1 73 39 78  9] [7] 5542.014
[ 1 73 39 78  9] [5] 9935.214
[ 1 73 39 78  9] [4] 16117.96
[ 1 73 39 78  9] [0] 7268.82
3405.99 [108  15] 14
[21 23 15] [ 1 73 39 78  9] 6356.558
[21 23 15] [19  2] 10302.8566667
[21 23 15] [48 17] 26286.6166667
[21 23 15] [45 

[45  6 67  1 73 39 78  9] [55] 7861.5675
[45  6 67  1 73 39 78  9] [54] 4796.315
[45  6 67  1 73 39 78  9] [53] 4800.22
[45  6 67  1 73 39 78  9] [52] 9532.89375
[45  6 67  1 73 39 78  9] [51] 5878.8125
[45  6 67  1 73 39 78  9] [50] 7822.0875
[45  6 67  1 73 39 78  9] [49] 6294.11875
[45  6 67  1 73 39 78  9] [47] 4419.97125
[45  6 67  1 73 39 78  9] [46] 6748.26375
[45  6 67  1 73 39 78  9] [44] 8124.825
[45  6 67  1 73 39 78  9] [43] 8731.36
[45  6 67  1 73 39 78  9] [42] 5751.515
[45  6 67  1 73 39 78  9] [41] 7212.85875
[45  6 67  1 73 39 78  9] [40] 5375.2375
[45  6 67  1 73 39 78  9] [38] 4139.3775
[45  6 67  1 73 39 78  9] [37] 5981.40375
[45  6 67  1 73 39 78  9] [36] 6713.9775
[45  6 67  1 73 39 78  9] [34] 7166.03625
[45  6 67  1 73 39 78  9] [33] 6136.56875
[45  6 67  1 73 39 78  9] [32] 5579.23375
[45  6 67  1 73 39 78  9] [31] 4583.8525
[45  6 67  1 73 39 78  9] [30] 6596.99375
[45  6 67  1 73 39 78  9] [29] 10409.0975
[45  6 67  1 73 39 78  9] [27] 5819.735
[45  6 67  1 

[60 13 87 28 80 35] [82] 7412.22166667
[60 13 87 28 80 35] [81] 5196.015
[60 13 87 28 80 35] [79] 8234.89666667
[60 13 87 28 80 35] [77] 6672.785
[60 13 87 28 80 35] [76] 6328.25833333
[60 13 87 28 80 35] [75] 8997.995
[60 13 87 28 80 35] [74] 11269.1983333
[60 13 87 28 80 35] [72] 13706.1666667
[60 13 87 28 80 35] [71] 12350.3666667
[60 13 87 28 80 35] [69] 8260.14833333
[60 13 87 28 80 35] [68] 6215.915
[60 13 87 28 80 35] [66] 6937.525
[60 13 87 28 80 35] [64] 13674.6666667
[60 13 87 28 80 35] [63] 6908.39333333
[60 13 87 28 80 35] [62] 11705.9116667
[60 13 87 28 80 35] [61] 4697.22166667
[60 13 87 28 80 35] [59] 5345.17166667
[60 13 87 28 80 35] [58] 6633.065
[60 13 87 28 80 35] [57] 10569.1566667
[60 13 87 28 80 35] [55] 8099.19833333
[60 13 87 28 80 35] [54] 6440.01833333
[60 13 87 28 80 35] [53] 6529.82166667
[60 13 87 28 80 35] [52] 7195.05666667
[60 13 87 28 80 35] [51] 5374.42
[60 13 87 28 80 35] [50] 8273.49666667
[60 13 87 28 80 35] [49] 7004.13333333
[60 13 87 28 80 35] [4

[ 3 65 86 97] [36 19  2] 9499.21666667
[ 3 65 86 97] [94 16] 8952.315
[ 3 65 86 97] [25 14] 6102.19
[ 3 65 86 97] [70 20 56] 4650.17333333
[ 3 65 86 97] [21 23 15] 8839.95833333
[ 3 65 86 97] [48 17] 25621.175
[ 3 65 86 97] [99] 5975.0575
[ 3 65 86 97] [98] 7280.585
[ 3 65 86 97] [95] 7869.65
[ 3 65 86 97] [93] 5273.135
[ 3 65 86 97] [92] 6033.69
[ 3 65 86 97] [91] 5996.325
[ 3 65 86 97] [90] 8352.885
[ 3 65 86 97] [89] 8935.165
[ 3 65 86 97] [88] 8899.6575
[ 3 65 86 97] [85] 5709.38
[ 3 65 86 97] [84] 4858.9525
[ 3 65 86 97] [83] 6792.87
[ 3 65 86 97] [82] 5856.4225
[ 3 65 86 97] [81] 7502.56
[ 3 65 86 97] [79] 7393.82
[ 3 65 86 97] [77] 8601.84
[ 3 65 86 97] [76] 6559.425
[ 3 65 86 97] [75] 5456.515
[ 3 65 86 97] [72] 9699.9275
[ 3 65 86 97] [71] 19361.95
[ 3 65 86 97] [69] 12607.725
[ 3 65 86 97] [68] 5359.5825
[ 3 65 86 97] [66] 6288.98
[ 3 65 86 97] [63] 11256.2525
[ 3 65 86 97] [62] 14890.1
[ 3 65 86 97] [61] 5796.04
[ 3 65 86 97] [59] 7391.055
[ 3 65 86 97] [58] 6542.4825
[ 3 65

[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [84] 4549.77066667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [83] 5808.458
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [82] 6627.77933333
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [81] 5952.76866667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [79] 8174.598
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [77] 6434.98133333
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [76] 5927.66333333
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [75] 8074.57466667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [72] 12485.5706667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [71] 15162.6466667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [69] 10927.794
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [68] 6273.32133333
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [66] 5749.4
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [63] 8373.90666667
[45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [62] 14153.7246667
[45  6 67  1 73 39 78  9 96 60 

[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [30] 6465.04875
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [29] 9893.921875
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [27] 6445.45375
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [26] 9074.7725
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [24] 6056.9925
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [22] 8014.5225
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [18] 8062.11625
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [12] 5934.359375
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [11] 7543.334375
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [10] 10305.069375
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [8] 5586.935625
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [7] 5122.608125
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [5] 9096.145
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [4] 14051.63125
[84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] [0] 7037.156875
4564.115 [1

[25 14  8] [83] 8400.01333333
[25 14  8] [82] 8221.52
[25 14  8] [79] 8207.03
[25 14  8] [77] 8307.14666667
[25 14  8] [76] 7986.52333333
[25 14  8] [75] 9310.95
[25 14  8] [72] 12419.2666667
[25 14  8] [69] 16757.6
[25 14  8] [68] 8343.26666667
[25 14  8] [66] 5813.47666667
[25 14  8] [63] 12093.4466667
[25 14  8] [62] 20316.0666667
[25 14  8] [59] 8812.97
[25 14  8] [57] 16760.4666667
[25 14  8] [55] 11095.6033333
[25 14  8] [54] 5802.94
[25 14  8] [52] 11495.08
[25 14  8] [51] 7484.38666667
[25 14  8] [50] 8803.30666667
[25 14  8] [49] 8805.63
[25 14  8] [46] 10115.3066667
[25 14  8] [44] 9523.89333333
[25 14  8] [43] 9692.08
[25 14  8] [42] 6814.68333333
[25 14  8] [41] 9085.87666667
[25 14  8] [40] 7718.38666667
[25 14  8] [37] 7799.92666667
[25 14  8] [34] 7816.54333333
[25 14  8] [32] 6349.04333333
[25 14  8] [30] 7709.49
[25 14  8] [29] 14129.0666667
[25 14  8] [26] 14865.3666667
[25 14  8] [24] 7382.42
[25 14  8] [22] 11026.6966667
[25 14  8] [18] 11407.1333333
[25 14  8] [12]

[ 5 94 16] [55] 9683.28666667
[ 5 94 16] [54] 11240.2633333
[ 5 94 16] [52] 7198.29666667
[ 5 94 16] [51] 7693.29333333
[ 5 94 16] [50] 14540.1666667
[ 5 94 16] [49] 9998.35333333
[ 5 94 16] [46] 6385.08
[ 5 94 16] [44] 16066.5666667
[ 5 94 16] [43] 16687.2
[ 5 94 16] [42] 9049.95333333
[ 5 94 16] [41] 9041.51333333
[ 5 94 16] [40] 11548.7
[ 5 94 16] [34] 14568.3333333
[ 5 94 16] [32] 15756.5
[ 5 94 16] [30] 10356.5833333
[ 5 94 16] [29] 12197.6333333
[ 5 94 16] [24] 8292.66
[ 5 94 16] [22] 9707.21
[ 5 94 16] [18] 9445.02666667
[ 5 94 16] [12] 9287.48
[ 5 94 16] [11] 11586.8666667
[ 5 94 16] [10] 9564.54
[ 5 94 16] [7] 7152.27333333
[ 5 94 16] [4] 14420.5
[ 5 94 16] [0] 8776.34333333
4789.96 [77 32] 44
[77 32] [ 5 94 16] 14092.2666667
[77 32] [93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35] 6426.1245
[77 32] [85 70 20 56 37] 10681.64
[77 32] [26 69] 13901.1
[77 32] [25 14  8] 7328.095
[77 32] [27 33] 10560.6525
[77 32] [53 58 61] 6607.03333333
[77 32] [38 21 23 15 81] 1124

[38 21 23 15 81 24] [91] 11739.8216667
[38 21 23 15 81 24] [90] 10652.4066667
[38 21 23 15 81 24] [89] 17033.4
[38 21 23 15 81 24] [88] 10187.445
[38 21 23 15 81 24] [82] 10573.22
[38 21 23 15 81 24] [79] 10946.085
[38 21 23 15 81 24] [76] 7840.88
[38 21 23 15 81 24] [75] 13024.5483333
[38 21 23 15 81 24] [72] 17422.0833333
[38 21 23 15 81 24] [68] 10446.6483333
[38 21 23 15 81 24] [66] 6925.61166667
[38 21 23 15 81 24] [62] 16931.5666667
[38 21 23 15 81 24] [59] 8719.605
[38 21 23 15 81 24] [57] 11294.5516667
[38 21 23 15 81 24] [55] 11698.3566667
[38 21 23 15 81 24] [54] 7293.47333333
[38 21 23 15 81 24] [52] 5784.23833333
[38 21 23 15 81 24] [51] 7675.885
[38 21 23 15 81 24] [50] 9621.37
[38 21 23 15 81 24] [49] 9979.52
[38 21 23 15 81 24] [46] 8838.725
[38 21 23 15 81 24] [43] 13004.6333333
[38 21 23 15 81 24] [42] 8664.11333333
[38 21 23 15 81 24] [41] 9200.25333333
[38 21 23 15 81 24] [40] 9400.115
[38 21 23 15 81 24] [34] 7484.75
[38 21 23 15 81 24] [30] 6780.06666667
[38 21 23 

[99 91] [52] 15379.45
[99 91] [51] 8287.505
[99 91] [50] 12292.2
[99 91] [49] 8368.0
[99 91] [43] 8168.295
[99 91] [42] 7189.335
[99 91] [41] 9325.435
[99 91] [40] 9217.51
[99 91] [34] 12041.7
[99 91] [30] 12405.2
[99 91] [29] 9936.61
[99 91] [22] 14180.1
[99 91] [18] 12333.65
[99 91] [12] 8584.7
[99 91] [11] 10232.15
[99 91] [10] 15044.4
[99 91] [4] 22769.1
[99 91] [0] 10047.615
5527.5025 [127 140] 54
[98 36 19  2 26 69] [99 91] 13299.25
[98 36 19  2 26 69] [53 58 61 54 25 14  8] 10638.537619
[98 36 19  2 26 69] [66 85 70 20 56 37] 13431.17
[98 36 19  2 26 69] [46  7] 6505.06
[98 36 19  2 26 69] [38 21 23 15 81 24] 9572.3275
[98 36 19  2 26 69] [83 63] 6603.6675
[98 36 19  2 26 69] [93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65 86 97] 7939.64993056
[98 36 19  2 26 69] [74 64 44] 21178.0444444
[98 36 19  2 26 69] [77 32] 9542.25333333
[98 36 19  2 26 69] [ 5 94 16] 6724.24944444
[98 36 19  2 26 69] [27 33] 10821.5666667
[98 36 19  2 26 69] [71 48 17] 9402.93611111
[

[38 21 23 15 81 24 52] [88] 10323.3814286
[38 21 23 15 81 24 52] [82] 11125.8314286
[38 21 23 15 81 24 52] [79] 11236.1585714
[38 21 23 15 81 24 52] [76] 8221.55428571
[38 21 23 15 81 24 52] [72] 18186.2857143
[38 21 23 15 81 24 52] [68] 10785.3557143
[38 21 23 15 81 24 52] [62] 16576.5142857
[38 21 23 15 81 24 52] [59] 8939.89
[38 21 23 15 81 24 52] [57] 10883.2471429
[38 21 23 15 81 24 52] [55] 11919.0628571
[38 21 23 15 81 24 52] [51] 7987.32
[38 21 23 15 81 24 52] [50] 9926.03142857
[38 21 23 15 81 24 52] [49] 10310.2171429
[38 21 23 15 81 24 52] [42] 9107.91142857
[38 21 23 15 81 24 52] [41] 9397.56
[38 21 23 15 81 24 52] [40] 9841.37
[38 21 23 15 81 24 52] [34] 7873.27142857
[38 21 23 15 81 24 52] [30] 6857.00714286
[38 21 23 15 81 24 52] [29] 17732.5285714
[38 21 23 15 81 24 52] [22] 7072.09428571
[38 21 23 15 81 24 52] [18] 10035.8171429
[38 21 23 15 81 24 52] [12] 8531.35714286
[38 21 23 15 81 24 52] [11] 10725.0242857
[38 21 23 15 81 24 52] [10] 13220.0571429
[38 21 23 15 81 

 28 80 35  3 65 86 97 46  7] [22] 8841.18235294
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [18] 8265.54852941
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [12] 6541.48911765
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [11] 8011.32176471
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [10] 10935.8464706
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [4] 14814.8235294
[53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] [0] 7761.81382353
6279.36541667 [157 151] 61
[74 64 44 43 66 85 70 20 56 37] [53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87
 28 80 35  3 65 86 97 46  7] 8096.56941176
[74 64 44 43 66 85 70 20 56 37] 

6543.89666667 [163  12] 66
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [95 38 21 23 15 81 24 52] 7510.73439189
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [68 18] 7494.95837838
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [74 64 44 43 66 85 70 20 56 37] 8154.59856757
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [75 99 91] 7597.29576577
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [98 36 19  2 26 69] 8563.14504505
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97 46  7 51 12] [83 63] 7971.26743243
[42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13
 87 28 80 35  3 65 86 97

7058.76666667 [143  62] 71
[ 5 94 16 62] [76 42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60
 13 87 28 80 35  3 65 86 97 46  7 51 12 59] 10469.2471154
[ 5 94 16 62] [83 63 98 36 19  2 26 69 88] 9298.47388889
[ 5 94 16 62] [95 38 21 23 15 81 24 52] 10386.0578125
[ 5 94 16 62] [68 18] 11501.94875
[ 5 94 16 62] [74 64 44 43 66 85 70 20 56 37] 14332.15625
[ 5 94 16 62] [75 99 91] 13450.8008333
[ 5 94 16 62] [77 32] 16249.1875
[ 5 94 16 62] [27 33] 11961.3825
[ 5 94 16 62] [71 48 17] 18079.3416667
[ 5 94 16 62] [90] 11849.515
[ 5 94 16 62] [89] 16792.0
[ 5 94 16 62] [82] 14200.8
[ 5 94 16 62] [79] 10599.07
[ 5 94 16 62] [72] 18539.65
[ 5 94 16 62] [57] 14822.075
[ 5 94 16 62] [55] 10626.19
[ 5 94 16 62] [50] 17042.0
[ 5 94 16 62] [49] 11108.94
[ 5 94 16 62] [41] 10540.735
[ 5 94 16 62] [34] 16464.35
[ 5 94 16 62] [30] 12624.7875
[ 5 94 16 62] [29] 12980.6
[ 5 94 16 62] [22] 11925.1075
[ 5 94 16 62] [11] 13223.55
[ 5 94 16 62] [10] 10810.905
[ 5 94 16 62] [4] 16688.75

7415.09296296 [172 176] 77
[30 95 38 21 23 15 81 24 52 27 33 22] [77 32 76 42 53 58 61 54 25 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9
 96 60 13 87 28 80 35  3 65 86 97 46  7 51 12 59 82] 7885.25154762
[30 95 38 21 23 15 81 24 52 27 33 22] [50 68 18] 10334.1808333
[30 95 38 21 23 15 81 24 52 27 33 22] [ 5 94 16 62] 10963.426875
[30 95 38 21 23 15 81 24 52 27 33 22] [83 63 98 36 19  2 26 69 88] 9392.2925
[30 95 38 21 23 15 81 24 52 27 33 22] [74 64 44 43 66 85 70 20 56 37] 10610.3209167
[30 95 38 21 23 15 81 24 52 27 33 22] [75 99 91] 12698.1113889
[30 95 38 21 23 15 81 24 52 27 33 22] [71 48 17] 22521.5027778
[30 95 38 21 23 15 81 24 52 27 33 22] [90] 10916.995
[30 95 38 21 23 15 81 24 52 27 33 22] [89] 17315.8916667
[30 95 38 21 23 15 81 24 52 27 33 22] [79] 11168.9941667
[30 95 38 21 23 15 81 24 52 27 33 22] [72] 17786.4333333
[30 95 38 21 23 15 81 24 52 27 33 22] [57] 11146.4225
[30 95 38 21 23 15 81 24 52 27 33 22] [55] 12011.7641667
[30 95 38 21 23 15 81 24 52 27 33 22] [49]

8726.11367816 [182 168] 83
[30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25 14  8 40 93
 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65 86 97 46  7
 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [79 74 64 44 43 66 85 70 20 56 37 75 99 91] 10054.1893284
[30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25 14  8 40 93
 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65 86 97 46  7
 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [ 5 94 16 62] 10752.684403
[30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25 14  8 40 93
 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65 86 97 46  7
 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [71 48 17] 19061.9389055
[30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25 14  8 40 93
 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65 86 97 46  7
 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [90] 9422.81492537
[30 95 38 21 23 15 81 24

9491.01571429 [ 90 187] 89
[90 49 41 11 30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25
 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65
 86 97 46  7 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [34 79 74 64 44 43 66 85 70 20 56 37 75 99 91] 10134.5704225
[90 49 41 11 30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25
 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65
 86 97 46  7 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [55 29] 10649.0252817
[90 49 41 11 30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25
 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65
 86 97 46  7 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 69 88] [ 5 94 16 62] 10804.9661268
[90 49 41 11 30 95 38 21 23 15 81 24 52 27 33 22 77 32 76 42 53 58 61 54 25
 14  8 40 93 31 47 92 84 45  6 67  1 73 39 78  9 96 60 13 87 28 80 35  3 65
 86 97 46  7 51 12 59 82 50 68 18  0 83 63 98 36 19  2 26 6

19289.9637684 [196 197] 98
inf [198 199] 99


KeyError: 199

In [34]:
finalanswer = np.array(finalanswer)
for i in range(97):
    if (finalanswer[i][0] != arr2[i][0] or finalanswer[i][1] != arr2[i][1]) and (finalanswer[i][1] != arr2[i][0] or finalanswer[i][0] != arr2[i][1]):
        print (finalanswer[i], arr2[i])

In [80]:
finalanswer = np.array(finalanswer)
np.savetxt('../h_outputbrute', finalanswer, delimiter=',', fmt='%i')

In [110]:
originalbrute = np.loadtxt('../h_output_newbrute', delimiter=',')
mab = np.loadtxt('../h_output_new', delimiter=',')
mab = np.array(mab, dtype='int')

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: loadtxt: Empty input file: "../h_output_newbrute"
  """Entry point for launching an IPython kernel.


In [111]:
for i in range(97):
    a = finalanswer[i][1:]
    a.sort()
    b = mab[i][1:]
    b.sort()
    if not np.array_equal(a,b):
        print (a,b, np.array_equal(a,b), i, gp[a[0]], gp[a[1]], M[a[0]][a[1]], M[b[0]][b[1]])

[17, 48] [ 2 19] False 11 [17] [48] 3161.29 3276.29
[2, 19] [106 107] False 12 [2] [19] 3276.29 3329.915
[106, 107] [ 15 108] False 13 [39 78  9] [ 1 73] 3329.915 3405.99
[15, 108] [ 35 109] False 14 [15] [21 23] 3405.99 3461.115
[35, 109] [ 70 104] False 15 [35] [13 87 28 80] 3461.115 3470.85
[70, 104] [17 48] False 16 [70] [20 56] 3470.85 3161.29
[110, 113] [110 112] False 17 [45  6 67] [ 1 73 39 78  9] 3553.626 8360.35333333
[36, 112] [ 36 111] False 20 [36] [19  2] 3598.705 11148.75
[60, 115] [ 60 114] False 22 [60] [13 87 28 80 35] 3742.924 6529.16333333
[64, 74] [ 97 121] False 25 [64] [74] 3956.32 4003.87666667
[97, 121] [ 98 120] False 26 [97] [ 3 65 86] 4003.87666667 4031.15333333
[98, 120] [53 58] False 27 [98] [36 19  2] 4031.15333333 4068.93
[53, 58] [ 85 115] False 28 [53] [58] 4068.93 8792.152
[85, 116] [44 74] False 29 [85] [70 20 56] 4093.70666667 4061.68
[38, 114] [ 38 113] False 30 [38] [21 23 15] 4142.75333333 3631.638
[71, 111] [ 71 116] False 32 [71] [48 17] 4350.2

In [61]:
finalanswer

[[100, 78, 9],
 [101, 45, 6],
 [102, 3, 65],
 [103, 28, 80],
 [104, 20, 56],
 [105, 13, 87],
 [106, 39, 100],
 [107, 1, 73],
 [108, 21, 23],
 [109, 105, 103],
 [110, 101, 67],
 [111, 48, 17],
 [112, 19, 2],
 [113, 107, 106],
 [114, 108, 15],
 [115, 109, 35],
 [116, 70, 104],
 [117, 110, 113],
 [118, 25, 14],
 [119, 94, 16],
 [120, 36, 112],
 [121, 102, 86],
 [122, 60, 115],
 [123, 117, 96],
 [124, 31, 47],
 [125, 74, 64],
 [126, 121, 97],
 [127, 98, 120],
 [128, 53, 58],
 [129, 85, 116],
 [130, 38, 114],
 [131, 123, 122],
 [132, 71, 111],
 [133, 130, 81],
 [134, 84, 131],
 [135, 128, 61],
 [136, 92, 134],
 [137, 93, 124],
 [138, 27, 33],
 [139, 118, 8],
 [140, 26, 69],
 [141, 129, 37],
 [142, 137, 136],
 [143, 5, 119],
 [144, 77, 32],
 [145, 125, 44],
 [146, 142, 126],
 [147, 83, 63],
 [148, 133, 24],
 [149, 135, 54],
 [150, 46, 7],
 [151, 66, 141],
 [152, 149, 139],
 [153, 99, 91],
 [154, 127, 140],
 [155, 146, 150],
 [156, 75, 153],
 [157, 145, 43],
 [158, 148, 52],
 [159, 40, 155],


In [98]:
M[87][28]

2600.27